### ISSUE TITLE
Search query param encoding

### ISSUE THREAD

**Issue by shedrachokonofua** [spotify-api/spotify-api.js#10]
# Bug Report

## My version of spotify-api.js
5.0.3

## What i expected...
Results for queries that contain spaces

## But what happened is...
```
const album = (await this.client.albums.search("Made In Lagos", {
      limit: 1,
})) as Album;
// Result: album = []
```
This search returned an empty response but when I made the equivalent curl request I received results. Tried a few more searches and noticed a pattern of queries with spaces not working.

**Comment by Scientific-Guy** [comment]
Actually, you have to kindly wait for thr v6 release of it, which will release near next week. It will have string typings. v5 has some damage which we noticed after release. v6 will be released as bug fix. We are sorry which you are facing.

**Comment by abh80** [comment]
Hey there , thanks for reaching us and looking into this problem , also i have edited your issue body to fix a major typo we made in `issue_template`.
