### ISSUE TITLE
Client.create is not a static method

### ISSUE THREAD

**Issue by peterjuras** [spotify-api/spotify-api.js#102]
# Bug Report

## What i expected:

I wanted to use `const client = await Client.create(...);` as specified in the example.

## What actually happened:

TypeScript complains that create doesn't exist on the Client class:

![image](https://user-images.githubusercontent.com/3640638/146497148-72b62bf6-127b-4ec0-91ed-8055dc526f49.png)

Looking into the source code, create appears to be a Class member, and not a static method.

## To reproduce this bug:

This [codesandbox](https://codesandbox.io/s/sad-ardinghelli-m9q5p?file=/src/index.ts) shows the same error

- Node Version: 16.13.0
- Library Version: 9.0.1

- [X] I have already checked issues regarding this bug.
- [] This problem is generated due to version migration.

**Comment by Kuplynx** [comment]
Same issue for me btw

**Comment by Kuplynx** [comment]
Just figured it out for ya. You just have to do const client = new Client({..args})

**Comment by scientific-dev** [comment]
Yeah it is a mistake in code. We will fix it quickly and notify you when the new version is ready.

Btw sorry for the late reply.

**Comment by peterjuras** [comment]
@scientific-dev No worries, thank you for creating and working on this! You also might want to add tests  to ensure that everything works as intended.

Keep up the good work!

**Comment by scientific-dev** [comment]
I have fixed the error above and released a new version [v9.0.2](https://github.com/spotify-api/spotify-api.js/releases/tag/9.0.2). I have also updated the documentation. 

If you find any further bugs in the package or in the documentation kindly open an new issue.
