### ISSUE TITLE
Use eventemitter

### ISSUE THREAD

**Issue by OkScript** [spotify-api/spotify-api.js#29]
# Feature Request

## Simple subject of my feature...
Using eventemitter.

## Feature description in brief...
I have viewed the documentation and found that there are no events to know when cache is ready. But then i found this on **README**

```js
const Client = new Spotify.Client("USER_TOKEN", { cacheCurrentuser: true });

function onCacheReady(){
    console.log('Client cache is ready!');
}

if(!Client.madeCache) Client.cacheOnReady = onCacheReady;
else onCacheReady();
```

This seems ugly. Can you use guys `events` package so the code looks like this:

```js
client.on('ready', ...
```
Something like discord.js? It would be fine right?

**Comment by Scientific-Guy** [comment]
I accept the fact that the code looks ugly. But we made that method just for temporary purpose. This thing probably will be updated on v8 of this package. And using `events` package for just 1 event is pointless and worthless. We would better use a ready method in the `CacheOptions` interface or somewhat. But thanks for sharing your idea!

**Comment by OkScript** [comment]
In that case you can actually make events like `debug`, `rateLimit` and `error`!

**Comment by Scientific-Guy** [comment]
Idea is good but it will not be good for a package like `spotify-api.js`. And `spotify-api.js` aims to be a bit small and fast!

**Comment by OkScript** [comment]
Well this was a suggestion.
