### ISSUE TITLE
spotify-api-js-org documentation typo's

### ISSUE THREAD

**Issue by Sellular** [spotify-api/spotify-api.js#31]
In [this](https://spotify-api.js.org/example/Authenication) page, there are some typos in the `const user` code block.

- clientId should be clientID
- client_secret should be clientSecret
- redirect_uri should be redirectUri
Also, a small one, but 'Authentication' in the side bar 'Examples' has a typo as well: 'Authenication'

**Comment by Scientific-Guy** [comment]
You have made a small mistake here which i just now noticed is `redirect_uri` should not be changed to `redirectUri` instead should be changed to `redirectURL`. You can view the documentation [here](https://spotify-api.js.org/typedef/GetUserTokenOptions).

**Comment by Scientific-Guy** [comment]
Currently the documentation has been updated to the documentation repo but it might take time to be deployed.

**Comment by abh80** [comment]
Docs have been updated successfully.
Thanks for helping us out there !

**Comment by Scientific-Guy** [comment]
> Docs have been updated successfully.
> Thanks for helping us out there !

I guess it not deployed perfectly yet.

**Comment by Scientific-Guy** [comment]
Fixed typos. You can view the updated one [here](https://spotify-api.js.org/example/Authenication).
