### ISSUE TITLE
Bad request (400) on playlist image upload

### ISSUE THREAD

**Issue by Fluxanoia** [spotify-api/spotify-api.js#33]
I have had success creating new playlists and adding/filtering tracks, but when I try to upload a playlist image, I keep hitting a bad request error on the PUT:

```
export const createPlaylist = async (
    client : Client,
    throwError : (error : Error) => void,
) => {
    const playlistOptions : CreatePlaylist = {
        name: `...name...`,
        description: `...desc...`,
        public: false,
        collaborative: false,
    };
    const playlist = await client.playlists.create(playlistOptions).catch(throwError);
    if (playlist) {
        playlist.uploadImage(`data:image/jpeg;base64,...`);
    }
    return playlist;
}
```

The console on the Spotify docs [isn't capable of taking URIs](https://community.spotify.com/t5/Spotify-for-Developers/Is-this-endpoint-working/m-p/5093200), always outputting a bad request. So, I couldn't test it there.

The auth/playlist is certainly valid, since I can still add tracks to it successfully, and I have all the necessary scopes on my token. I have tried multiple image URIs, small and large, and they all give me the same error. I checked the library source and couldn't find any issues either (with respect to the [docs](https://developer.spotify.com/console/put-playlist-images/)).

Am I missing something?

This is on version 8.0.0.

**Comment by Scientific-Guy** [comment]
This would be better if you give the full traceback error which was displayed in the console.

**Comment by Fluxanoia** [comment]
Here is the traceback:

![error](https://user-images.githubusercontent.com/6279354/119629600-11a46600-be06-11eb-8139-df8c140ef6ac.png)

**Comment by abh80** [comment]
Hey thanks for reaching us out!
Please go to response section in network panel of the request and send us the report

**Comment by Fluxanoia** [comment]
I'm just getting:

```
{
  "error" : {
    "status" : 400,
    "message" : "Bad request."
  }
}
```

in those panels, no other information. Also, the image URI is here:

```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCACAAIADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5rooor8DP9oAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD/2Q==
```

IIRC it's just 128x128 plain colour, and certainly isn't >=256kB.

**Comment by abh80** [comment]
Thanks for the information ! Please wait for a while while I investigate this issue I will surely acknowledge you if I find the issue.

**Comment by abh80** [comment]
@Fluxanoia I got the issue fixed, The problem was that you had to remove the `data:image/jpeg;base64,` from the image url i.e it should be a plain simple base64 url without the `data:image/jpeg;base64,`.
For example this is what I did -
```js
const image = `/9j/4AA.......igD/2Q==`
playlist.uploadImage(image);
```
