### ISSUE TITLE
Could you add album skip?

### ISSUE THREAD

**Issue by shillshocked** [spotify-api/spotify-api.js#36]
I make playlists that contain full albums. It would be nice to have a method to skip to the first track of the next unique album.

**Comment by Scientific-Guy** [comment]
Do you mean you have a set of allbums where you have to play the first track of the each album? Sorry for the late response.

**Comment by Scientific-Guy** [comment]
Closing because its been 10 days without beign responded by the creator of the issue. Repoen this issue once ready to reply @shillshocked.
