### ISSUE TITLE
Unclear instrusctions

### ISSUE THREAD

**Issue by boingfromdiscord** [spotify-api/spotify-api.js#4]
hello I see on the documentation you guys use `const spotify = new Client("NO TOKEN");` what am I supposed to put in the strings because what ever I try I keep getting undefined from token

**Comment by abh80** [comment]
Hey there, thanks for joining us today.
It seems like the `documentation` is unclear to some users, I apologize for it.

But I will try my best to help you out with this issue,
While getting a token you can keep the token as anything rather it would be your previous token.
Here is an example of getting `Spotify` `access token` - >
```js
const {Client} = require('spotify-api.js')
const client = new Client('any')
client.oauth.get({
  client_id : "238fa6ea7adb4c4da04f35265d74d121",
  client_secret : "f403a4a5f6e44db09311671738585808"
}).then(token=>console.log(token))
```
And also I would like to suggest you to use the latest version `spotify-api.js` version from the [npm](https://www.npmjs.com/package/spotify-api.js) but incase you need the version number here it is - `3.0.2`.

If you need more help free feel to comment down below.
I would be happy to help you out :)

**Comment by abh80** [comment]
Hey there, thanks for joining us today.
It seems like the `documentation` is unclear to some users, I apologize for it.

But I will try my best to help you out with this issue,
While getting a token you can keep the token as anything rather it would be your previous token.
Here is an example of getting `Spotify` `access token` - >
```js
const {Client} = require('spotify-api.js')
const client = new Client('any')
client.oauth.get({
  client_id : "client id",
  client_secret : "client secret"
}).then(token=>console.log(token))
```
And also I would like to suggest you to use the latest version `spotify-api.js` version from the [npm](https://www.npmjs.com/package/spotify-api.js) but in case you need the version number here it is - `3.0.2`.

If you need more help free feel to comment down below.
I would be happy to help you out :)

**Comment by Scientific-Guy** [comment]
I prefer you to watch the readme docs first and then move up with the docs...
The readme will give u a clean way to move up

`Client` is nothing but `require('spotify-api.js').Client`

**Comment by Scientific-Guy** [comment]
I guess he has solved this issue...
Incase if you are back, reopen this issue...
