### ISSUE TITLE
Add scopes in spotify-types package.

### ISSUE THREAD

**Issue by tito400** [spotify-api/spotify-api.js#69]
https://github.com/spotify-api/spotify-api.js/blob/f0579b09e3b61fbfdc8491f6059c78bf891b9f24/src/Interface.ts#L272

Why not add this `Scopes` in the `spotify-types` package itself?

**Comment by scientific-dev** [comment]
The `spotify-types` package is supposed to only have types with no javascript code and `Scopes` here is an object. I will add it to `spotify-types` only if people want it like that.
