### ISSUE TITLE
Client.user is undefined with user authorized token. 

### ISSUE THREAD

**Issue by tintin10q** [spotify-api/spotify-api.js#83]
# Bug Report

## What I expected:
I expected the client to have a user property like the docs state. 

## What happened:
Instead client.user is undefined. 

## To reproduce this bug:
Get a token from Spotify. I am using the Authorization Code Flow with Proof Key for Code Exchange flow.
I am using enough scopes to get the user data. 

I make a client like this:

```js
import {Client, UserClient} from "spotify-api.js";

const token = get_token();
const client = await new Client({
      token,
      userAuthorizedToken: true,
      cacheSettings: { cacheUser: true }});
console.log(Client.user)
console.log(await new UserClient(client))
```

This gives me back: 
`undefined`
`UserClient {type: "user", player: Player, client: Client}`

Why is there no user property? The user client also does not have any of the properties described in the docs. 

However, if I open up the userclient in the console that does have a user property and actually has my user's information in there but if I access it then it is undefined. 

- Library Version:  v9.0.1

**Comment by scientific-dev** [comment]
Well there is a mistake in your code.

```js
const client = await new Client({
      token,
      userAuthorizedToken: true,
      cacheSettings: { cacheUser: true }});

console.log(Client.user);
```

Here you are accessing the `user` property from the `Client` class not the `client` object. Try doing it like


```js
console.log(Client.user);
```

**Comment by scientific-dev** [comment]
> I am expiring similar issue:
> 
> ```
>   await new SpotifyClient({
>     token: {
>       // redirectURL: "http://localhost/",
>       clientID: "",
>       clientSecret: "",
>     },
>     userAuthorizedToken: true,
> 
>     refreshToken: true,
>     async onReady(c) {
>       console.log(`🚀 ~ onReady ~ c.user;`, c.user);
>     },
>     onRefresh() {
>       consoleInfo("Refreshed Spotify token", "**\n**", null, true);
>     },
>   });```
>   
>   returning undefined
> ```

Kindly do not expose your client secret and client id @niveKKumar.

**Comment by niveKKumar** [comment]
> 

Thanks for your prompt message. That were a lot mistakes, I should ve checked
```js
export const spotifyApi = async () => {
  if (spotify) return spotify;
  spotify = await SpotifyClient.create({
    token: {
      // redirectURL: "http://localhost/",
      clientID: "",
      clientSecret: "",
    },
    userAuthorizedToken: true,
    refreshToken: true,
    onRefresh() {
      consoleInfo("Refreshed Spotify token", "**\n**", null, true);
    },
  });
};

async function test() {
  const kev = (await spotifyApi()).user
  console.log(`🚀 ~ test ~ kev`, kev);
}
test();
```

What am I missing here ? I want saved Podcasts to be loaded from the api, which as far I understand should work like this:

```
await kev.getSavedShows({})
````
But user here is undefined...

**Comment by scientific-dev** [comment]
> 

Well, here you are mistaken with something, you want to access the `current user` api for that you would require `code` and `redirectURL` fields in `token`.

```js
export const spotifyApi = async () => {
  if (spotify) return spotify;
  spotify = await SpotifyClient.create({
    token: {
      redirectURL: "redirect url here",
      code: "your code here",
      clientID: "",
      clientSecret: "",
    },
    userAuthorizedToken: true,
    refreshToken: true,
    onRefresh() {
      consoleInfo("Refreshed Spotify token", "**\n**", null, true);
    },
  });
return spotify;
};
```

**Comment by niveKKumar** [comment]
> Well, here you are mistaken with something, you want to access the `current user` api for that you would require `code` and `redirectURL` fields in `token`. So, the code would look something like this:
> 
> ```js
> export const spotifyApi = async () => {
>   if (spotify) return spotify;
>   spotify = await SpotifyClient.create({
>     token: {
>       redirectURL: "redirect url here",
>       code: "your code here",
>       clientID: "",
>       clientSecret: "",
>     },
>     userAuthorizedToken: true,
>     refreshToken: true,
>     onRefresh() {
>       consoleInfo("Refreshed Spotify token", "**\n**", null, true);
>     },
>   });
> return spotify;
> };
> ```

I want the user associated to my clientId, I have a pure node application (no website, express or anything similar).

**Comment by scientific-dev** [comment]
> niveKKumar

But if you want a client to access the `current user`, you would require those parameters through web server, even if you don't use this module, you have to go through the same process by using api methods.

There is one more way,

1. Get the access token using the express api (first time).
2. Create the client with the access token with the `refreshToken` option set to `true` so that when the access token gets expired, the client will regenerate a new token.

**Comment by niveKKumar** [comment]
> > niveKKumar
> 
> But if you want a client to access the `current user`, you would require those parameters through web server, even if you don't use this module, you have to go through the same process by using api methods.
> 
> There is one more way,
> 
> 1. Get the access token using the express api (first time).
> 2. Create the client with the access token with the `refreshToken` option set to `true` so that when the access token gets expired, the client will regenerate a new token.

I would need to do that upon every restart of the application right ?

**Comment by scientific-dev** [comment]
> > > niveKKumar
> > 
> > 
> > But if you want a client to access the `current user`, you would require those parameters through web server, even if you don't use this module, you have to go through the same process by using api methods.
> > There is one more way,
> > 
> > 1. Get the access token using the express api (first time).
> > 2. Create the client with the access token with the `refreshToken` option set to `true` so that when the access token gets expired, the client will regenerate a new token.
> 
> I would need to do that upon every restart of the application right ?

Yeah. When the program restarts, you want to change your access token to the last refresh token. 

You can solve this issue by the following:

1. Get the initial token through spotify web api or through spotify web api dashboard.
2. Save the token in some sort of database.
3. Whenever the program starts, get the token from the database and use it as an access token.
4. And save the new access token whenever the module refreshes the token using the `onRefresh` event.

**Comment by niveKKumar** [comment]
Appreciate your help, just only problem I have. I was able to retrieve my access token and my refreshtoken
![image](https://user-images.githubusercontent.com/48483421/167401275-e41b3216-8c6d-454f-91a7-7dc233fa7647.png)
How can i pass it to my client spotify client ?
I passed my earlier application credits from my spotify app and also passed my retrieved refresh token, which still returns my user (Client#user) as undefined

**Comment by scientific-dev** [comment]
> Appreciate your help, just only problem I have. I was able to retrieve my access token and my refreshtoken ![image](https://user-images.githubusercontent.com/48483421/167401275-e41b3216-8c6d-454f-91a7-7dc233fa7647.png) How can i pass it to my client spotify client ? I passed my earlier application credits from my spotify app and also passed my retrieved refresh token, which still returns my user (Client#user) as undefined

You can create the `Client` with the following options,

```js
await SpotifyClient.create({
    token: 'Your access token',
    userAuthorizedToken: true,
    refreshToken: true,
    onReady (client) {
        // Setup details
        client.refreshMeta = {
              clientID: "",
              clientSecret: "",
              refreshToken: ""
        };
    },
    onRefresh () {
        consoleInfo("Refreshed Spotify token", "**\n**", null, true);
    },
  });
```

With this code, you will get a stack trace on console saying `[SpotifyClientWarn]: You have provided a token and used `refreshToken` option. Try to provide clientID, clientSecret or user authenication details.`. You can ignore that warning.

> The warning is because the current spotify version doesn't support direct current user access token. This will be fixed in the upcoming version.

If you get any different errors, you can reply it here.

**Comment by scientific-dev** [comment]
With the latest release of [v9.1.0](https://github.com/spotify-api/spotify-api.js/releases/tag/9.1.0), you can do it like this without a lot of mess,

```js
const client = await Client.create({
     userAuthorizedToken: true,
     refreshToken: true,
     token: {
          accessToken: "access token here",
          clientID: "client id",
          clientSecret: "client secret",
          redirectURL: "redirect url here"
    }

    // Your other options...
});
```

**Comment by niveKKumar** [comment]
Thats the syntax:

```
 token: {
        token: t != undefined ? t : (await getSpotifyAccessToken())?.token,
        ...credit,
      },
      ```
      
      Spotify doesnt give the hours right ? Only the day
      So I could only check for hourly changes through comparing to my cache

**Comment by scientific-dev** [comment]
> Thats the syntax:
> 
> ```
>  token: {
>         token: t != undefined ? t : (await getSpotifyAccessToken())?.token,
>         ...credit,
>       },
> ```
> 
> ```
>   Spotify doesnt give the hours right ? Only the day
>   So I could only check for hourly changes through comparing to my cache 
> ```

It should be `token: { accessToken }`.
And about the releaseDate issue, are you talking about the releaseDate of `Show`s?

**Comment by niveKKumar** [comment]
![image](https://user-images.githubusercontent.com/48483421/167478367-7c0d6868-51c7-4fd3-82c9-179f559b4bcb.png)

Yes I am talking about shows, seems that the api doesnt give any option to get a more precise date...

**Comment by scientific-dev** [comment]
> ![image](https://user-images.githubusercontent.com/48483421/167478367-7c0d6868-51c7-4fd3-82c9-179f559b4bcb.png)
> 
> Yes I am talking about shows, seems that the api doesnt give any option to get a more precise date...

My mistake. It was supposed to be `accessToken`. Now, I guess let it be like that.

And about the precise release date of Shows, the spotify api does not provides it. [Source](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-show)

But, if i find any way to get the precise release date, i will let you know.

**Comment by niveKKumar** [comment]
> > ![image](https://user-images.githubusercontent.com/48483421/167478367-7c0d6868-51c7-4fd3-82c9-179f559b4bcb.png)
> > 
> > Yes I am talking about shows, seems that the api doesnt give any option to get a more precise date...
> 
> My mistake. It was supposed to be `accessToken`. Now, I guess let it be like that.
> 
> And about the precise release date of Shows, the spotify api does not provides it. [Source](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-show)
> But, if i find any way to get the precise release date, i will let you know.

Comparing new Shows with the cache would give a more precise date not?

Like I fetch every 1 hour the episodes and a new episode pops up which isn't in the cache. You could atleast give an hourly timeframe (date) for the new episode right?

**Comment by scientific-dev** [comment]
> > > ![image](https://user-images.githubusercontent.com/48483421/167478367-7c0d6868-51c7-4fd3-82c9-179f559b4bcb.png)
> > > Yes I am talking about shows, seems that the api doesnt give any option to get a more precise date...
> > 
> > 
> > My mistake. It was supposed to be `accessToken`. Now, I guess let it be like that.
> > And about the precise release date of Shows, the spotify api does not provides it. [Source](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-show)
> > But, if i find any way to get the precise release date, i will let you know.
> 
> Comparing new Shows with the cache would give a more precise date not?
> 
> Like I fetch every 1 hour the episodes and a new episode pops up which isn't in the cache. You could atleast give an hourly timeframe (date) for the new episode right?

Yeah, initially I had the same idea and wanted to add this feature to this module. But, this might result in continuous fetch requests which may increase ratelimits but if its for every 1 hour, then its not an issue. This feature is not added to the module yet because it would make module more complicated. 

Moreover, you cannot trust on cache since when the program restarts, the cache will be empty. You have to use a database and save the IDs of the episodes.

The idea would work since most of the third party notification service use the same method. You can implement this feature in your project. In future, i will try to create a separate module for such methods.

**Comment by niveKKumar** [comment]
```
onRefresh() {
        consoleInfo("Refreshed Spotify token", `**${spotify.token} \n**`, null, true);
        new SpotifyLog({ token: spotify.token }).save().then(() => {
          consoleInfo("Refreshed spotify and saved to db", null, null, true);
        });
      },
      ```
      The token is much shorter then my access token i obtain manually
      Using the safed token it throws the Error 

```       statusText: 'Unauthorized',```

**Comment by scientific-dev** [comment]
> @scientific-dev
> 
> ### The token is much shorter then my access token i obtain manually
> ```
>   Using the saved token it throws the Error 
> 
> 
>   statusText: 'Unauthorized',
> ```
> 
> ```
> onRefresh() {
>         consoleInfo("Refreshed Spotify token", `**${spotify.token} \n**`, null, true);
>         new SpotifyLog({ token: spotify.token }).save().then(() => {
>           consoleInfo("Refreshed spotify and saved to db", null, null, true);
>         });
>       },
> ```

What is the issue here?

**Comment by niveKKumar** [comment]
With the give token (spotify.token), I cant create a new Client...
The returned token is also much shorter than the "normal" access token

![image](https://user-images.githubusercontent.com/48483421/167624009-60a58319-9ad6-420f-9044-bd2d58b4801b.png)


```
export const spotifyApi = async (t = manual) => {
  // if (spotify) return spotify;
  // await SpotifyLog({ token: manual }).save();
  try {
    spotify = await SpotifyClient.create({
      userAuthorizedToken: true,
      token: {
        token: t != undefined ? t : (await getSpotifyAccessToken())?.token,
        ...credit,
      },
      refreshToken: true,
      async onRefresh() {
        consoleInfo("Refreshed Spotify token", `**${spotify.token} \n**`, null, true);
        new SpotifyLog({ token: spotify.token }).save().then(() => {
          consoleInfo("Refreshed spotify and saved to db", null, null, true);
        });
        console.log(await spotifyApi(spotify.token));
      },
    });
  } catch (error) {
    console.log(`🚀 ~ spotifyApi ~ Catched`, error);
  }
  Sleep(4000).then(() => {
    spotify.refreshFromMeta();
  });
  return spotify;
};
```

**Comment by scientific-dev** [comment]
> With the given token (spotify.token), I cant create a new Client... The returned token is also much shorter than the "normal" access token I can login first with my manual token, the onRefresh throws the Error then...
> 
> ![image](https://user-images.githubusercontent.com/48483421/167624009-60a58319-9ad6-420f-9044-bd2d58b4801b.png)
> 
> ```js
> export const spotifyApi = async (t = manual) => {
>   // if (spotify) return spotify;
>   // await SpotifyLog({ token: manual }).save();
>   try {
>     spotify = await SpotifyClient.create({
>       userAuthorizedToken: true,
>       token: {
>         token: t != undefined ? t : (await getSpotifyAccessToken())?.token,
>         ...credit,
>       },
>       refreshToken: true,
>       async onRefresh() {
>         consoleInfo("Refreshed Spotify token", `**${spotify.token} \n**`, null, true);
>         new SpotifyLog({ token: spotify.token }).save().then(() => {
>           consoleInfo("Refreshed spotify and saved to db", null, null, true);
>         });
>         console.log(await spotifyApi(spotify.token));
>       },
>     });
>   } catch (error) {
>     console.log(`🚀 ~ spotifyApi ~ Catched`, error);
>   }
>   Sleep(4000).then(() => {
>     spotify.refreshFromMeta();
>   });
>   return spotify;
> };
> ```

I guess, you still don't understand, you do not have to worry about the refreshing the token for every hour or particular duration limit, the module itself would refresh the token if the `refreshToken` option is set to true. If you have supplied the required refresh options in `token`, it would refresh itself whenever it receives an `access token expired` response.

**Comment by niveKKumar** [comment]
Yeah I know and thats great on this module as it handles it itself

My problem is, that I want to have only the information of a specific user (mine) to get its shows, but I have a node only enviroment, no browser with logging in. You suggested me to 

Get the initial token through spotify web api or through spotify web api dashboard.
Save the token in some sort of database.
Whenever the program starts, get the token from the database and use it as an access token.
And save the new access token whenever the module refreshes the token using the onRefresh event.

Which is what i am trying here with the code, but it doesnt work through obtaining the new token from the client, as you can see in the onRefresh creating a new Client with the new token from the client

**Comment by scientific-dev** [comment]
> Yeah I know and thats great on this module as it handles it itself
> 
> My problem is, that I want to have only the information of a specific user (mine) to get its shows, but I have a node only enviroment, no browser with logging in. You suggested me to
> 
> Get the initial token through spotify web api or through spotify web api dashboard. Save the token in some sort of database. Whenever the program starts, get the token from the database and use it as an access token. And save the new access token whenever the module refreshes the token using the onRefresh event.
> 
> Which is what i am trying here with the code, but it doesnt work through obtaining the new token from the client, as you can see in the onRefresh creating a new Client with the new token from the client @scientific-dev Appreciate your help !

Why are you creating another client? You can use the same client right?

**Comment by peterjuras** [comment]
This is still happening for me. `client.user` is undefined. This is my initialization code:

```ts
const client = await Client.create({
    token: {
      clientID: spotifyConfig.SPOTIFY_CLIENT_ID,
      clientSecret: spotifyConfig.SPOTIFY_CLIENT_SECRET,
      refreshToken: spotifyUser.refreshToken,
    },
    userAuthorizedToken: true,
    refreshToken: true,
  });

// client.user is not defined.
```

**Comment by scientific-dev** [comment]
> This is still happening for me. `client.user` is undefined. This is my initialization code:
> 
> ```ts
> const client = await Client.create({
>     token: {
>       clientID: spotifyConfig.SPOTIFY_CLIENT_ID,
>       clientSecret: spotifyConfig.SPOTIFY_CLIENT_SECRET,
>       refreshToken: spotifyUser.refreshToken,
>     },
>     userAuthorizedToken: true,
>     refreshToken: true,
>   });
> 
> // client.user is not defined.
> ```

I didn't noticed this bug and thanks for noticing it and telling us. This issue is fixed in [v9.2.1](https://github.com/spotify-api/spotify-api.js/releases/tag/9.2.1). Try running it in the newer version.

**Comment by peterjuras** [comment]
Thanks, it works correctly now 👍 🙌

**Comment by scientific-dev** [comment]
> Thanks, it works correctly now 👍 🙌

Your welcome.
